In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(0,50,10)

array([ 0, 10, 20, 30, 40])

In [ ]:
np.linspace(0,50,6)

array([ 0., 10., 20., 30., 40., 50.])

In [ ]:
np.random.rand(10)

array([0.85067852, 0.69397941, 0.43151937, 0.81320974, 0.17583527,
       0.12379369, 0.69717235, 0.03056697, 0.00626913, 0.33070485])

In [ ]:
np.random.rand(2,3)

array([[0.25732083, 0.36030015, 0.09368009],
       [0.35083188, 0.72818756, 0.43964783]])

In [ ]:
np.random.randint(1,6)

1

last number is exclusive in randint

In [ ]:
np.random.randint(1,7,10)

array([6, 2, 6, 1, 2, 6, 2, 2, 1, 5])

np.random.randint(1,7,10)--> this will generate random number from 1-6 ,and the amount/quantity  of numbers will be 10

In [ ]:
my_array=np.random.randint(1,10,6)

In [ ]:
my_array

array([1, 6, 1, 7, 3, 5])

In [ ]:
my_array.max()

7

In [ ]:
my_array.min()

1

In [ ]:
my_array.argmax()

3

In [ ]:
my_array.argmin()

0

In [ ]:
new_array=my_array.reshape(2,3)

my_array.reshape(2,3) ---> this will convert the array into 2 rows and 3 columns , however it can also be turn into 3,2

In [ ]:
new_array.shape

(2, 3)

In [ ]:
my_array

array([1, 6, 1, 7, 3, 5])

In [ ]:
my_array[1]=5

In [ ]:
my_array

array([1, 5, 1, 7, 3, 5])

In [ ]:
arr1=my_array.copy()

In [ ]:
arr1

array([1, 5, 1, 7, 3, 5])

In [ ]:
arr1[0]=20

In [ ]:
arr1

array([20,  5,  1,  7,  3,  5])

In [ ]:
arr2d=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [ ]:
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

arr2d[1][1]-----> this will enable to track any particular element

In [ ]:
arr2d[1][1]

50

In [ ]:
arr2d[2][1]

80

In [ ]:
arr2d[2,1]

80

In [ ]:
arr2d[1:,1:]

array([[50, 60],
       [80, 90]])

In [ ]:
my_array

array([1, 5, 1, 7, 3, 5])

In [ ]:
array3=my_array>5

In [ ]:
array3

array([False, False, False,  True, False, False])

In [ ]:
my_array+my_array

array([ 2, 10,  2, 14,  6, 10])

In [ ]:
my_array-my_array

array([0, 0, 0, 0, 0, 0])

In [ ]:
my_array/my_array

array([1., 1., 1., 1., 1., 1.])

In [ ]:
my_array*my_array

array([ 1, 25,  1, 49,  9, 25])